window.__NSP_GAME_CHUNKS=window.__NSP_GAME_CHUNKS||[];window.__NSP_GAME_CHUNKS.push("function makeReceipt(state='manual'){const data={game:'The Dark Below',state,depth,lantern:Math.ceil(oil),fear:Math.round(fear*100),generated_at:new Date().toISOString()};$('receipt').textContent=JSON.stringify(data,null,2);return data}
function loop(){const now=performance.now(),stepMs=1000/60,steps=Math.max(1,Math.min(10,Math.round((now-lastUpdate)/stepMs)));lastUpdate=now;for(let i=0;i<steps;i++)update();setTimeout(loop,stepMs)}
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','q','Q','f','F'].includes(e.key))e.preventDefault();keys[e.key]=true;if(!e.repeat&&(e.key==='q'||e.key==='Q'))toggleLight();if(!e.repeat&&(e.key==='f'||e.key==='F'||e.key===' '))useFlare()},{passive:false});document.addEventListener('keyup',e=>{keys[e.key]=false});window.addEventListener('blur',()=>keys={});
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;const on=e=>{e.preventDefault();keys[k]=true};const off=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});
$('start').onclick=()=>{audio();if(AC&&AC.resume)AC.resume();reset()};$('lightBtn').onclick=toggleLight;$('flareBtn').onclick=useFlare;$('touchLight').onclick=toggleLight;$('touchFlare').onclick=useFlare;$('receiptBtn').onclick=()=>makeReceipt(won?'covenant-restored':over?'taken':'manual');
$('soundBtn').onclick=()=>{soundOn=!soundOn;$('soundBtn').textContent='Sound: '+(soundOn?'On':'Off');$('soundBtn').setAttribute('aria-pressed',String(soundOn));if(master)master.gain.value=soundOn?.36:0;if(soundOn&&AC&&AC.resume)AC.resume()};
$('safeBtn').onclick=()=>{sensorySafe=!sensorySafe;$('safeBtn').textContent='Sensory: '+(sensorySafe?'Safe':'Full');$('safeBtn').setAttribute('aria-pressed',String(sensorySafe));$('warn').textContent=sensorySafe?'Sensory Safe active: flashes and sharp stingers are suppressed.':'Contains stylized pursuit, controlled flashes, and dynamic sound. Sensory Safe removes flashes and sharp stingers.'};
window.__darkBelowWave20={get atlasReady(){return atlasReady},snapshot:()=>({started,running,won,over,tick,depth,room:room&&room.name,hunter:room&&hunterNames[room.hunter],fragments,oil:Math.round(oil),fear:+fear.toFixed(2),threads,lightMode,player:player&&{x:Math.round(player.x),y:Math.round(player.y)},sensorySafe}),start:reset,toggleLight,useFlare,collect:i=>collectShard(i),setHunter:i=>{if(!room)return;room={...room,hunter:Math.max(0,Math.min(2,i|0))};hunter.x=W/2;hunter.y=120;updateHud()},stageHero:()=>{if(!player||!hunter)return;player.x=930;player.y=515;hunter.x=625;hunter.y=235;hunter.stun=0;hunter.alert=1;lightMode='search';flare=70;updateHud()},scare:()=>{if(!hunter||!player)return;hunter.x=player.x-54;hunter.y=player.y-22;hunter.alert=1;caught()}};
pathFloor();loop();draw();
})();
